# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

CONFIG_CHALLENGE_SETTINGS = "CHALLENGE_SETTINGS"
CONFIG_CHALLENGE_ID = "ID"
CONFIG_CHALLENGE_NAME = "NAME"
CONFIG_CHALLENGE_GOAL = "GOAL"
CONFIG_CHALLENGE_DESCRIPTION = "DESCRIPTION"
CONFIG_CHALLENGE_FLAG = "FLAG"

CONFIG_SCORING_SETTINGS = "SCORING_SETTINGS"
CONFIG_SCORING_SUBMISSION_ENDPOINT = "SUBMISSION_ENDPOINT"
CONFIG_SCORING_KEY = "API_KEY"
CONFIG_SCORING_SCORING_ENDPOINT = "SCORING_ENDPOINT"

CONFIG_REDIS_URL = "REDIS_URL"
CONFIG_STORAGE_ACCOUNT_URL = "STORAGE_ACCOUNT_URL"
CONFIG_STORAGE_CONTAINER_NAME = "STORAGE_CONTAINER_NAME"

CONFIG_AUTH_SETTINGS = "AUTH_SETTINGS"
CONFIG_AUTH_TYPE = "TYPE"

CONFIG_CTFD_SETTINGS = "CTFD"
CONFIG_CTFD_REDIRECT_URL = "REDIRECT_URL"
CONFIG_CTFD_URL = "CTFD_URL"
CONFIG_CTFD_REDIS_URL = "REDIS_URL"
CONFIG_CTFD_SECRET_KEY = "SECRET_KEY"

